import "./globals.css";
import {Providers} from "@/app/components/Providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className="dark">
        <body className="min-h-screen bg-gradient-to-b from-[#111111] to-[#383120]">
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
